# Generated by Django 4.1.7 on 2023-02-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='baseRole',
            new_name='role',
        ),
    ]
