version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
      - ./app/media:/app/media
    env_file:
      - .env
    environment:
      - DEBUG=0

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
      - ./app/media:/app/media
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data: