# Generated by Django 4.1.7 on 2023-02-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1024)),
                ('sent', models.BooleanField(default=False)),
                ('arrived', models.BooleanField(default=False)),
                ('payment_session', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('payed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='products')),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branduserprofile')),
            ],
            options={
                'unique_together': {('slug', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('bought', models.BooleanField(default=False)),
                ('data_time', models.DateTimeField(blank=True, null=True)),
                ('price_on_buying', models.IntegerField(blank=True, default=None, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shopperprofile')),
                ('command', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.command')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
